import 'package:flutter/material.dart';
import 'dart:js_interop';
import 'package:web/web.dart' as web;
import '../models/payment_record.dart';
import '../services/pdf_report_service.dart';
import '../utils/constants.dart';
import '../widgets/shared_screen_components.dart';

class PaymentReportScreen extends StatelessWidget {
  final List<PaymentRecord> payments;

  const PaymentReportScreen({super.key, required this.payments});

  @override
  Widget build(BuildContext context) {
    final totalExpected =
        payments.fold<int>(0, (sum, payment) => sum + payment.amount);
    final totalCollected = payments
        .where((payment) => payment.isPaid)
        .fold<int>(0, (sum, payment) => sum + payment.amount);
    final totalPending = totalExpected - totalCollected;
    final collectionRate = totalExpected == 0
        ? 0
        : ((totalCollected / totalExpected) * 100).round();
    final arrears = payments.where((payment) => payment.isPending).toList();
    final propertyBreakdown = buildPropertyBreakdown(payments);

    return FeatureScaffold(
      title: 'Payment Report',
      accentColor: AppColors.kodiGreen,
      child: ListView(
        padding: const EdgeInsets.all(18),
        children: [
          ReportDocumentCard(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const PaymentReportHeader(
                  generatedDate: '19 May 2026',
                  period: 'May 2026',
                ),
                const SizedBox(height: 18),
                const LandlordReportInfo(),
                const SizedBox(height: 18),
                PaymentReportSummary(
                  totalExpected: totalExpected,
                  totalCollected: totalCollected,
                  totalPending: totalPending,
                  collectionRate: collectionRate,
                ),
                const SizedBox(height: 18),
                PropertyBreakdownTable(rows: propertyBreakdown),
                const SizedBox(height: 18),
                DetailedPaymentTable(payments: payments),
                const SizedBox(height: 18),
                ArrearsTable(payments: arrears),
                const SizedBox(height: 18),
                ReportCharts(
                  propertyRows: propertyBreakdown,
                  totalCollected: totalCollected,
                  totalPending: totalPending,
                ),
                const SizedBox(height: 18),
                const Divider(color: AppColors.border),
                const SizedBox(height: 10),
                const Row(
                  children: [
                    Expanded(
                      child: Text(
                        'Generated by KodiPay',
                        style: TextStyle(
                          color: AppColors.kodiNavy,
                          fontWeight: FontWeight.w800,
                        ),
                      ),
                    ),
                    Text('support@kodipay.co.ke  |  Page 1'),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 18),
          Row(
            children: [
              Expanded(
                child: ElevatedButton.icon(
                  onPressed: () async {
                    final pdfService = PdfReportService();
                    await pdfService.generatePaymentReport(
                      landlordName: 'Johnnie Njenga',
                      landlordEmail: 'njengajohnnie@gmail.com',
                      landlordPhone: '+254 700 000 000',
                      propertyCount: 3,
                      totalExpected: totalExpected,
                      totalCollected: totalCollected,
                      totalPending: totalPending,
                      period: 'May 2026',
                      payments: payments.map((p) => {
                        'tenant': p.tenantName,
                        'unit': p.unit,
                        'property': p.property,
                        'amount': money(p.amount),
                        'status': p.status,
                        'date': p.paidAt ?? '-',
                      }).toList(),
                      propertyBreakdown: propertyBreakdown.map((pb) => {
                        'name': pb.propertyName,
                        'units': pb.units.toString(),
                        'collected': money(pb.collected),
                        'pending': money(pb.pending),
                      }).toList(),
                      arrears: arrears.map((a) => {
                        'tenant': a.tenantName,
                        'unit': a.unit,
                        'amount': money(a.amount),
                        'days': '${a.daysLate} days',
                      }).toList(),
                      barChartData: propertyBreakdown.map((pb) => {
                        'label': pb.propertyName,
                        'value': pb.collected,
                      }).toList(),
                      pieCollected: totalCollected,
                      piePending: totalPending,
                    );
                  },
                  icon: const Icon(Icons.picture_as_pdf_rounded),
                  label: const Text('Download PDF'),
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: OutlinedButton.icon(
                  onPressed: () {
                    final csv = StringBuffer();
                    csv.writeln('Tenant,Unit,Property,Amount,Status,Date');
                    for (final p in payments) {
                      csv.writeln('${p.tenantName},${p.unit},${p.property},${p.amount},${p.status},${p.paidAt ?? '-'}');
                    }
                    final blob = web.Blob([csv.toString().toJS].toJS, web.BlobPropertyBag(type: 'text/csv'));
                    final url = web.URL.createObjectURL(blob);
                    web.HTMLAnchorElement()..href = url
                      ..setAttribute('download', 'payment_report_May2026.csv')
                      ..click();
                    web.URL.revokeObjectURL(url);
                  },
                  icon: const Icon(Icons.table_chart_outlined),
                  label: const Text('CSV'),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

